### ISSUE TITLE
Ans some questions.

### ISSUE THREAD

**Issue by addhome2001** [jsnoveya/react-prac-todo#1]
A1: 會導致這個錯誤提示是因為，一開始`InputField `元件的state是undefined（React稱之為uncontrolled component），但是之後卻又因為input的onChange同步了（React稱之為controlled component），React不允許你這樣切換元件，問題出在一開始定義state時。`'' || undefined` 得到的其實是undefined，因為空自串在js中代表false，所以||會返回右邊的值。

A2: onBlur以及其他添加事件監聽的props一樣，不需要由父組件傳遞，除非handler需要參考父組件以上的state，所以只要像其他事件監聽一樣添加就好（例如：onChange）。

A3: switch case的`case`和`情形`建議要用空格分開喔。

**Comment by jsnoveya** [comment]
Tks1:  undefined 現象是缺了父組件App傳送的props, 已加入`text={''}`, 並把InputField的state定義改成`value: this.props.text`, 就沒err了。(已commit修改)

Tks2: InputField分別被父:App、父:Item, 所呼叫, Item的toggleMode()需要被子InputField的onBlur觸發, 以切換顯示模式, 所以設了props;  但父:App不需要被觸發。 這種狀況該如何處理呢?  

Tks3: 非常感謝喔。(已commit修改)

**Comment by jsnoveya** [comment]
Tks2: 從A1發現到沒給的props回傳undefined, 所以我做了判斷式來解決我的提問2, `this.props.onBlur===undefined? e.preventDefault(): this.props.onBlur()` , (再次commit修改)

**Comment by addhome2001** [comment]
進步很快！👍
